### ISSUE TITLE
NPM module not updated to latest release

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [vladikoff/node-geckodriver#10]
Hi :)

I noticed you updated the code five days ago to use the latest geckodriver. However, the version in NPM hasn't been updated, so it downloads the 0.10.0 version instead.

Cheers! :)

**Comment by vladikoff** [comment]
Huh, should be there : https://www.npmjs.com/package/geckodriver

![image](https://cloud.githubusercontent.com/assets/128755/19855683/3eaae3a0-9f4c-11e6-9cb3-2aa4483594b4.png)
