### ISSUE TITLE
Please support mozilla geckodriver 0.32.0 and Linux aarch64 architecture

### ISSUE THREAD

**Issue by rbruckheimer** [vladikoff/node-geckodriver#107]
This was just released:
https://github.com/mozilla/geckodriver/releases/tag/v0.32.0
It supports Linux aarch64 architecture, which does not seem to be currently detectable by this node-geckodriver package.
Can you make the Linux aarch64 architecture-compatible tar downloadable via this package?

It's located here: https://github.com/mozilla/geckodriver/releases/download/v0.32.0/geckodriver-v0.32.0-linux-aarch64.tar.gz
Note this is the earliest version available for the Linux aarch64, if you want to throw an error message if an earlier version is requested, that would be nice.

**Comment by vladikoff** [comment]
Try version 3.2.0!
