### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by zdglagola** [vladikoff/node-geckodriver#17]
Legal policy at work requires a valid LICENSE file for importing external libraries. Love to leverage this library if we can add one. Perhaps MIT for popularity https://github.com/blog/1964-open-source-license-usage-on-github-com :)

**Comment by vladikoff** [comment]
https://github.com/vladikoff/node-geckodriver/blob/master/package.json#L22

**Comment by vladikoff** [comment]
done https://github.com/vladikoff/node-geckodriver/blob/master/LICENSE

**Comment by zdglagola** [comment]
You rock. Thanks.
