### ISSUE TITLE
Add geckodriver to the bin field of package.json

### ISSUE THREAD

**Issue by jeffposnick** [vladikoff/node-geckodriver#2]
It would be very helpful to have the downloaded `geckodriver` listed in the [`bin`](https://docs.npmjs.com/files/package.json#bin) field of `package.json`, to automatically set up a symlink in `node_modules/.bin` after it's installed.

That's what the `chromedriver` package [does](https://github.com/giggio/node-chromedriver/blob/master/package.json#L26).

**Comment by vladikoff** [comment]
ah yess! good idea

**Comment by vladikoff** [comment]
hm I wonder what we should do for Windows though :\

**Comment by jeffposnick** [comment]
Does the approach used by `chromedriver` work on Windows? (I don't have a Windows machine handy to try.)

**Comment by vladikoff** [comment]
Ah I see what that module does. The main issue is the difference in the way the drivers work.

I think chromedriver runs on a port. 
while geckodriver is passed as a capability (but might also just work as a process)

**Comment by jeffposnick** [comment]
I'm planning on using it with Selenium, and as per [Mozilla's docs](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver#Add_executable_to_system_path), that requires the `geckodriver` executable to be available somewhere in `$PATH`.

`node_modules/.bin` would be the standard, project-local place that's in `$PATH`, with the assumption that the script which is loading Selenium will be started via `npm run`.

**Comment by vladikoff** [comment]
Ok great, I'll draft something up to make it use `.bin`

**Comment by vladikoff** [comment]
Fixed in `v1.1.1`. Hopefully it works for you on the first try! 🎁

**Comment by jeffposnick** [comment]
Thanks so much, @vladikoff!

**Comment by jstockwin** [comment]
@vladikoff I'm struggling to get this working on Windows. 
```
"webdriver.gecko.driver": "node_modules/geckodriver/geckodriver.exe"
```
It works fine if I give the full path like that, but simply doing
```
"webdriver.gecko.driver": "node_modules/.bin/geckodriver"
```
Doesn't seem to work. Am I missing something?
