### ISSUE TITLE
Cannot install behind a proxy

### ISSUE THREAD

**Issue by stevehipwell** [vladikoff/node-geckodriver#21]
The **got** library that is used to download the binary does not seem to respect *http_proxy* or *https_proxy* meaning that this package cannot be downloaded behind our corporate proxy.

**Comment by vladikoff** [comment]
@stevehipwell https://github.com/sindresorhus/got/issues/79

**Comment by stevehipwell** [comment]
@vladikoff my point is why are you using **got** which doesn't support proxies when there are plenty of other libraries for downloading files that do?

[chromedriver](https://github.com/giggio/node-chromedriver) works ([almost](https://github.com/giggio/node-chromedriver/issues/91)) correctly. 
[phantomjs-prebuilt](https://github.com/Medium/phantomjs) works correctly.

**Comment by Kikketer** [comment]
I'm reverting to 2.24.1 until this issue is resolved.  The build complexities inside a corporate firewall are annoying as hell, and it used to work until version 2.28.  Even getting the binaries and putting them within the application are annoying since the build servers we use randomly create folders.

**Comment by vladikoff** [comment]
Let me know if a custom CDN url helps with this:  
https://github.com/vladikoff/node-geckodriver#setting-a-cdn-url-for-binary-download

Reopen if still needed something extra

**Comment by stevehipwell** [comment]
@vladikoff - How would a custom CDN help with a proxy issue? The issue in question here is your use of `got` and their [refusal](https://github.com/sindresorhus/got/issues/200) to support proxy variables. Please can you switch to using a http library that respects the system _http_proxy_ and _https_proxy_ variables?

**Comment by vladikoff** [comment]
Hey @stevehipwell ,

> How would a custom CDN help with a proxy issue?

You can host the file yourself and point it to a location where your corporate proxy has access.

> their refusal to support proxy variables

I don't think they *refused*. The proxy support issue is still open here: https://github.com/sindresorhus/got/issues/79

> Please can you switch to using a http library that respects the system http_proxy and https_proxy variables?

That might work, looks like `request` has support for this: https://github.com/request/request/blob/643c43ab7be269a1efaa080ff05a18fff3f64cd7/README.md#controlling-proxy-behaviour-using-environment-variables

**Comment by stevehipwell** [comment]
@vladikoff - Switching to `request` would be the perfect solution.

Having to maintain a separate file inside a corporate network is not really an option.

I take the following '*A good PR would be accepted, but won't happen from my part.*' as a refusal from the author.

**Comment by mk-pmb** [comment]
Having the same problem. How about a fallback to wget if there's a non-empty env var that ends in `_proxy`?
