### ISSUE TITLE
Replace tar.gz (deprecated) with tar

### ISSUE THREAD

**Issue by julia-r** [vladikoff/node-geckodriver#35]
[tar.gz](https://www.npmjs.com/package/tar.gz) is not maintained anymore, could you switch to [tar](https://www.npmjs.com/package/tar) instead? 

(I can try to make a pull request, but I haven't tried it before, so it might take a bit)

**Comment by brianvoe** [comment]
+1

**Comment by vladikoff** [comment]
Fixed in https://github.com/vladikoff/node-geckodriver/commit/e4715edfd866ec4a63298df168db5c2054381fbd
