### ISSUE TITLE
Version 1.10.0 Is a breaking change version

### ISSUE THREAD

**Issue by asRIA** [vladikoff/node-geckodriver#37]
Hi, Version 1.10.0 started to use new tar package, what started to require Node.js 6+
Previously this package was Node.js 4x compatible.

**Comment by vladikoff** [comment]
@asRIA You need node 4.5 please update to that: https://github.com/npm/node-tar/blob/master/package.json#L37

**Comment by asRIA** [comment]
So, regardless the minimum required version has changed. This could be highlighted a little bit more.

Nevertheless, Thanks for your reply.

**Comment by vladikoff** [comment]
@asRIA yeah sorry, I looked at their .travis.yml and it was still node `4`, so i assumed it's all good. Hopefully it's not too much work for you to update to 4.5!

**Comment by vladikoff** [comment]
@asRIA if it's a lot of work for you and others we can explore other options of fixing this up

**Comment by asRIA** [comment]
Not so much, it was more like a surprise. I've bought some time by setting an explicit version of the geckodriver. Thx!
