### ISSUE TITLE
NPM install not working

### ISSUE THREAD

**Issue by Niek** [vladikoff/node-geckodriver#41]
I tried on several machines but always get this error:

```
$ npm -g install geckodriver
/usr/bin/geckodriver -> /usr/lib/node_modules/geckodriver/bin/geckodriver

> geckodriver@1.11.0 postinstall /usr/lib/node_modules/geckodriver
> node index.js

Downloading geckodriver... events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open 'geckodriver.tar.gz'
Emitted 'error' event at:
    at WriteStream.onerror (/usr/lib/node_modules/geckodriver/node_modules/readable-stream/lib/_stream_readable.js:640:52)
    at WriteStream.emit (events.js:180:13)
    at fs.open (fs.js:2224:12)
    at FSReqWrap.oncomplete (fs.js:153:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! geckodriver@1.11.0 postinstall: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the geckodriver@1.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by vladikoff** [comment]
why are you installing it globally with a `-g`? that's not supported

**Comment by Niek** [comment]
My bad... [this article](https://mykzilla.org/2017/08/30/headless-firefox-in-node-js-with-selenium-webdriver/) suggested installing it globally.

**Comment by vladikoff** [comment]
@Niek try adding it as a dependency to your project. If you install it globally you might get into a mess of different geckodriver versions what you don't want to deal with

**Comment by hodnett** [comment]
I had the same problem using Amazon Linux, both with and without the global flag. In a nutshell, if you clone your node.js project to a directory owned by root and execute npm install using sudo privileges, the actual step of extracting geckodriver.tar.gz is **_not_** executed by root or with sudo, but instead with your original privileges. The workaround is to recursively chmod the project folder itself as npm install not only needs to be able to write to node_modules, but also needs to touch the both the package.json and package-lock.json files. (I don't detect any differences to package.json but it is what it is.)
