### ISSUE TITLE
Automatically Finding Driver

### ISSUE THREAD

**Issue by gauntface** [vladikoff/node-geckodriver#6]
Do you know what it would take for this module to be automatically picked up by selenium?

I was originally downloading geckodriver and then renaming it to wires which was the name for geckodriver / marionette at one point (or that's the impression I get). The advantage of this is that I didn't need to define a path for geckodriver.

**Comment by gauntface** [comment]
Another thing I realized while trying this out, I got an error when trying to use the driver and when running 

    geckodriver --version

It would throw a segfault. I hit this a while ago, either I was downloading the package incorrectly or I was extracting it correctly (Can't recall which though).

**Comment by gauntface** [comment]
Another Comment (sorry for dumping these here).

The readme's suggestion seems out of date. selenium-webdriver 3.0.0 expects useGeckoDriver() to be used to enable / disable geckodriver - it's on by default.

I can't see how to define the path of where the gecko driver lives but the profile setting didn't work.

I did get it to work by installing the 'geckodriver' file to somewhere on the PATH (i.e. the root of the project running selenium)

**Comment by vladikoff** [comment]
How does chromedriver work in this case? You have to manually start it up right?

**Comment by vladikoff** [comment]
I just published v1.1.2, it should now work the same as https://github.com/giggio/node-chromedriver#running-with-selenium-webdriver

require('geckodriver');
require('chromedriver');
var webdriver = require('selenium-webdriver');

**Comment by vladikoff** [comment]
https://github.com/SeleniumHQ/selenium/issues/2600

**Comment by bertolo1988** [comment]
I got this error:
> Error: The geckodriver.exe executable could not be found on the current PATH. Please download the latest version from https://github.com/mozilla/geckodriver/releases/WebDriver and ensure it can be found on your PATH.

I am using `geckodriver@1.1.2`.
