### ISSUE TITLE
Upgrade tar dependency to >= 6.1.2 (high vulnerability reported by npm audit)

### ISSUE THREAD

**Issue by st-schaefer** [vladikoff/node-geckodriver#94]
tar 6.1.0 has a high vulnerability and should be upgraded to >= 6.1.2

see: 
https://npmjs.com/advisories/1770
https://npmjs.com/advisories/1771

**Comment by vladikoff** [comment]
should be fixed

**Comment by st-schaefer** [comment]
Perfect. Thanks!
